/*
  # Create inquiries table

  1. New Tables
    - `inquiries`
      - `id` (bigint, primary key)
      - `created_at` (timestamp with time zone)
      - `name` (text, not null)
      - `phone` (text, not null)
      - `location` (text, not null)
      - `product` (text, not null)
      - `message` (text)
  2. Security
    - Enable RLS on `inquiries` table
    - Add policy for authenticated users to read and insert data
    - Add policy for anonymous users to insert data
*/

-- Create the inquiries table
CREATE TABLE IF NOT EXISTS inquiries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  location text NOT NULL,
  product text NOT NULL,
  message text
);

-- Enable Row Level Security
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Allow authenticated users to read inquiries" 
  ON inquiries 
  FOR SELECT 
  TO authenticated 
  USING (true);

CREATE POLICY "Allow authenticated users to insert inquiries" 
  ON inquiries 
  FOR INSERT 
  TO authenticated 
  WITH CHECK (true);

-- Allow public users to insert inquiries (for unauthenticated form submissions)
CREATE POLICY "Allow public to insert inquiries" 
  ON inquiries 
  FOR INSERT 
  TO anon 
  WITH CHECK (true);